orlaudc/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from django.contrib.auth.views import login

from cas_client import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'orlaudc.views.home', name='home'),
    # url(r'^orlaudc/', include('orlaudc.foo.urls')),

    url (r'^$', csrf_exempt(TemplateView.as_view(template_name="home.html")),
            name='home'),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^cas/', include('cas_client.urls')),

    url(r'^accounts/login/$',
    		TemplateView.as_view(template_name="accounts_login.html"),
    		name='accounts_login'),

    url(r'^accounts/local_login$', login, name="login"),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

)
urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

from polls import views

# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote$', views.vote, name='vote'),

    url(r'^(?P<poll_id>\d+)/add_choice$', views.add_choice, name='add_choice'),


    url(r'^(?P<poll_id>\d+)/bulk$', permission_required("polls.bulk")(TemplateView.as_view(template_name="polls/bulk_form.html")), name='bulk'),
    url(r'^(?P<poll_id>\d+)/bulk/upload$', views.bulk_upload, name='bulk_upload'),

)

polls/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Count
from django.utils import timezone


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.question

    def get_votes(self):
        return Vote.objects.all_sorted(self)

    class Meta:
        permissions = (
            ('poll_view', 'Can view polls'),
            ('poll_create', 'Can create a poll'),
            ('poll_vote', 'Can vote in polls'),
            ('poll_results', 'Can view the results of a poll'),
            ('poll_details', 'Can view all the details of a poll'),
            ('bulk', 'Can update choices in bulk'),
            ('full_results', 'Can view the points of each individual choice')
        )

class ChoiceManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ChoiceManager, self).all(*args, **kwargs).order_by('choice_text')


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    suggested_by = models.ForeignKey(get_user_model())

    choice_text = models.CharField(max_length=200, unique=True)
    post_date = models.DateTimeField('date posted', default=timezone.now)

    objects = ChoiceManager()

    def __unicode__(self):
        return self.choice_text


class VoteManager(models.Manager):
    def all_sorted(self, poll):

        choices = Choice.objects.filter(poll=poll)
        qs = self.filter(choice__in=choices)
        # qs = qs.order_by('number__sum')
        # qs = qs.extra(select={ 'nsum' : 'SUM(number)' }, order_by='-nsum')
        qs = qs.select_related('choice').values('choice__choice_text').annotate(models.Sum('number'), models.Count('number')).order_by('-number__count', '-number__sum')

        print qs
        print "hola!"
        return qs

    def get_users(self):
        x = self.values("user").annotate(Count("id")).order_by()

        print x
        return x



class Vote(models.Model):
    choice = models.ForeignKey(Choice)
    user = models.ForeignKey(get_user_model())

    number = models.IntegerField()
    post_date = models.DateTimeField('date posted', default=timezone.now)

    objects = VoteManager()

    def __unicode__(self):
        return u"{0}p: {1} -> {2}".format(self.number, self.user, self.choice)

polls/views.py
# -*- coding: utf-8 -*-
# Create your views here.

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views import generic

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages

from polls.models import Choice, Poll, Vote


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        #if not request.user.is_authenticated():
        #    return HttpResponseRedirect(reverse('accounts_login'))
        return super(IndexView, self).get(request, *args, **kwargs)


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        # print self.__dict__
        context['user_votes'] = Vote.objects.filter(user_id=self.request.user.id)

        print list(context['user_votes'])
        return context

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('accounts_login'))
        return super(DetailView, self).get(request, *args, **kwargs)


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

    @method_decorator(permission_required('polls.poll_results'))
    def dispatch(self, request, *args, **kwargs):
        return super(ResultsView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('accounts_login'))

        return super(ResultsView, self).get(request, *args, **kwargs)


@permission_required("polls.bulk")
def bulk_upload(request, poll_id, *args, **kwargs):
    # Delete them all first
    Choice.objects.all().delete()

    created_len = 0
    data = request.POST['data']
    sep = request.POST['sep'] or "\n"

    data_rows = data.split(sep)

    for datum in data_rows:
        datum = datum.strip()
        if not datum:
            continue
        choice, created = Choice.objects.get_or_create(choice_text=datum, poll_id=poll_id, defaults={"suggested_by": request.user})
        if created:
            created_len += 1;

    return HttpResponse("Created %d records." % created_len)


def validate_vote(request_fields, allowed_range, request=None):
    item_values = []
    for key, value in filter(lambda (k, v): 'choice_' in k, request_fields.iteritems()):
        value = int(value)
        key = key[len('choice_'):]
        if value in item_values or value not in allowed_range:
            if request:
                choice = Choice.objects.get(pk=key).choice_text
                messages.debug(request, u"Key = %s (%s), Value = %s, item_values = {%s}, allowed_range = %s" % (key, choice, value, item_values, allowed_range))
            return False
        item_values.append(value)
    return True


@login_required
def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)

    # First of all, delete all votes for this user
    Vote.objects.filter(user=request.user).delete()

    # Filter empty votes
    votes = {}
    for key, value in request.POST.iteritems():
        if value == "0":
            print "Request for key ", key, " not appended"
            continue
        votes[key] = value

    # Validate votes
    if not validate_vote(votes, range(0, 11), request):
        messages.warning(request, u"A votación non pasa a validación interna. Qué carallo andas a facer?")

    else:
        for key, value in filter(lambda (k, v): 'choice_' in k, votes.iteritems()):
            key = key[len('choice_'):]
            cur_choice = Choice.objects.get(pk=key)

            cur_vote, created = Vote.objects.get_or_create(
                number=value, user=request.user,
                defaults={"choice": cur_choice}
            )

            cur_vote.choice = cur_choice
            cur_vote.save()
        messages.success(request, u"Votos rexistrados con éxito.")

    return HttpResponseRedirect(reverse('polls:detail', args=(poll_id,)))

def add_choice(request, poll_id):
    pass

polls/templates/polls/bulk_form.html
{%extends "site_base.html" %}
{% block title %}Orla UDC: Formulario de subida de opcións en bruto{% endblock %}
{% block content %}

<form action="{% url "polls:bulk_upload" poll_id %}" method="POST">
{% csrf_token %}

<label>
	Insire aquí os nomes das opcións.
<textarea name="data">

</textarea>
</label>

<label>Separador entre opcións:
	<input type="text" class="input-small" name="sep" value=";" />
</label>

<input type="submit" name="submit" value="Insertar" />

<!--
<input type="submit" name="del" value="Eliminar existentes" />
-->
</form>

{% endblock %}

polls/templates/polls/detail.html
{%extends "site_base.html" %}
{% block title %}Orla UDC: Detalle de votación{% endblock %}
{% block style %}

.sortable {
	min-height: 0px;
	border: 1px dotted black;
	padding: 40px;
	margin:0
}

{% endblock %}
{% block content %}

<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="messages">
{% for message in messages %}
<div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
<button type="button" class="close" data-dismiss="alert">&times;</button>
{{ message }}</li>
</div>
{% endfor %}
</div>

<p>
Teranse en conta as 10 primeiras eleccións. Quedan <span class="remaining_votes"></span>.
</p>

<h2>Instruccións</h2>
<ul>
	<li>Cada persoa pode escoller <strong>10 opcións</strong></li>
	<li>Pódese cambiar o voto volvendo a enviar o formulario (as votacións antigas perderanse)</li>
	<li>Para elexir unha opción pódese arrastrar e soltar</li>
	<li>Tamén se pode <strong>pulsar no texto</strong> da opción para seleccionar o cuadro do número e poñer nel os puntos que se lle queiran dar a esa opción</li>
	<li>Os números á esquerda indican <strong>a puntuación</strong>, co cal as primeiras opcións da lista serán as que maior puntuación teñan</li>
	<li>Esta puntuación <strong>só</strong> se terá en conta para a elección do <strong>padriño</strong>, para que sexa máis dificil que ocorran empates</li>
	<li>O resto de votos computan o mesmo (8 votos de 1 punto valen máis ca 7 votos de 9 puntos para a aparición na orla)</li>
	<li><strong>Se engadides unha opción nova, esta queda engadida e non pode ser modificada a posteriori</strong> <small>e sábese quén a engadiu</small></li>
	<li>É irrelevante a cantidade de elementos que se poñan con puntuación de 0. A partir da décima elección, os demais non contan en absoluto</li>
</ul>

<noscript>Aviso, necesítase JavaScript para que funcione correctamente esta encuesta.</noscript>

<div id="choices">
<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}

<ul id="sortable" class="sortable">
</ul>

<input type="submit" value="Vote" />
</form>

<ul id="sortable_notform" class="sortable">
</ul>
</div>


<form id="addToListForm" action="{% url 'polls:add_choice' poll.id %}" method="post">
{% csrf_token %}

<fieldset>
	<p>Falta algunha opción aquí?</p>

	<div class="input-append" style="display:inline">
		<input type="text" id="choice_plus_text" placeholder="Vacío" value="" />
		<button id="addToListBtn" class="btn" type="button">Engadir á lista</button>
	</div>
</fieldset>

</form>


<script type="text/javascript">


function draw_choice(id, name) {
	/*
	 * Draws a choice in the not-punctuable field
	 */
	obj = $('#sortable_notform')

	var li = document.createElement('li')
	var label = document.createElement('label')
	var inpt = document.createElement('input')
	inpt.type = "text"
	$(inpt).attr('placeholder', '1..10')
	$(inpt).val(0)
	$(inpt).attr('data-value', 0)
	inpt.id = "choice_" + id
	inpt.name ="choice_" + id
	inpt.className = "input-mini"

	label.appendChild(inpt)
	label.innerHTML += " " + name

	li.appendChild(label)

	obj.append(li)

	attach_on_change(id)
}

function swapdiv_choice(cur_obj, onlyup) {
	var cur_obj = $(cur_obj).parent().parent()
	var dest_obj = null
	var containers = [ $('#sortable'), $('#sortable_notform') ]
	if(onlyup) {
		dest_obj = containers[0]
	} else
		for (var x = 0; x < containers.length; x++)
			if(cur_obj.parent() != containers[x]) {
				dest_obj = containers[x]
				break
			}
	cur_obj.detach().appendTo(dest_obj)
}

function drawswap_choice(id, newname) {
	var obj = $('input[type=text]').filter(function(idx, dom) {
		return dom.id == "choice_" + id
	})
	var parent = obj.parent()
	parent.html("")
	parent.append(obj)
	parent.append(" ")
	parent.append(newname)
}

$(function() {
	{% for choice in poll.choice_set.all %}
	draw_choice({{ choice.id }}, "{{ choice.choice_text|force_escape|escapejs }}")
	{% endfor %}

{% if user_votes %}
	var user_votes = Array(11);
		{% for vote in user_votes %}
	user_votes[{{ vote.number }}] = {{ vote.choice.id }};{% endfor %}

	for(var i = 10; i >= 0; i--) {
		if(user_votes[i]) {
			var obj = document.getElementById('choice_' + user_votes[i]);
			obj.value = i;
			swapdiv_choice(obj, true)
		}
	}

{% endif %}


	// sort_list($('#sortable'));
})


function sort_list(list) {
	var lis = $(list.children().get().reverse())
	// console.log(lis)
	var first_idx = lis.length - 11

	lis.each(function(idx, dom) {
		// console.log(first_idx, lis.length, idx)
		var i = idx - first_idx
		$(dom).find('input[type=text]').val((i >= 0 ? i : 0))
		$(dom).find('input[type=text]').attr('data-value', i)
	})

	$('.remaining_votes').html(10 - lis.length)

}

function sort_dom_list(evt) {
	var mylist = $('#sortable')

	console.log(evt)
	swapdiv_choice(evt.target, true)
	var lis = mylist.children('li').get()

	lis.sort(function(a, b) {
		var $a = $(a).find('input[type=text]')
		var $b = $(b).find('input[type=text]')

		var a_val, b_val;

		a_val = ($a.val() < $a.attr('data-value')) ? $a.val() - 1 : $a.val() + 1
		b_val = ($b.val() < $b.attr('data-value')) ? $b.val() - 1 : $b.val() + 1

		a_val = parseInt($a.val())
		b_val = parseInt($b.val())

		if(a_val == b_val) {
			if(a_val > $a.attr('data-value') || b_val > $b.attr('data-value'))
				return -1
			else
				return 1
		}

		return (a_val < b_val) ? -1 : 1
	})

	lis.reverse()

	$.each(lis, function(idx, item) {
		mylist.append(item)
	})

	sort_list(mylist)
}

function visual_warn(message)
{
    $('.messages').append('<div id="alertdiv" class="alert alert-warning"><a class="close" data-dismiss="alert">×</a><span>'+message+'</span></div>')

    setTimeout(function() { // this will automatically close the alert and remove this if the users doesnt close it in 5 secs
      $("#alertdiv").remove();

    }, 5000);
}


	$(function() {
		$( "#sortable" ).sortable({
			stop: function(evt, ui) {
						sort_list($("#sortable"));
					},
			cancel: '.ui-state-disabled',
			connectWith: '.sortable',
			distance: 15,
			placeholder: "ui-state-highlight"
		});
		// $( "#sortable" ).disableSelection();
		$( "#sortable_notform" ).sortable({
			stop: function(evt, ui) {
					sort_list($("#sortable"));
				},
			cancel: '.ui-state-disabled',
			connectWith: '.sortable',
			distance: 15,
			placeholder: "ui-state-highlight"
		})

		$( ".score_input" ).change(sort_dom_list)

		sort_list($("#sortable"))
	});

	$( "#addToListBtn" ).click(function() {
		var text = $('#choice_plus_text').val()
		// console.log('hello', text)
		Dajaxice.polls.add_choice(Dajax.process, {"poll_id": {{ poll.id }}, "text": text})
	})

	$( "#addToListForm" ).submit(function() {
		// console.log('hello', text)
		var text = $('#choice_plus_text').val()
		Dajaxice.polls.add_choice(Dajax.process, {"poll_id": {{ poll.id }}, "text": text})
	})

	function attach_on_change(choice_id) {
		$('#choice_' + choice_id).change(sort_dom_list)
		// sort_list($('#sortable'))
	}

	function add_ajax_error(text) {
		var d = document.createElement('div')
		var btn = document.createElement('button')
		d.className = 'alert alert-warning'
		btn.type = 'button'
		btn.className = 'close'
		$(btn).attr('data-dismiss', 'alert')
		btn.innerHTML = '&times;'
		d.appendChild(btn)
		d.innerHTML += text

		$('.messages')[0].appendChild(d)
	}

</script>

{% endblock %}

polls/templates/polls/index.html
{%extends "site_base.html" %}
{% block title %}Orla UDC: Lista de Votacións{% endblock %}
{% block content %}

{% if latest_poll_list %}
	<ul>
	{% for poll in latest_poll_list %}
		<li>
			{% if poll.is_active %}
			<a href="{% url "polls:detail" poll.id %}">
				{{ poll.question }}
			</a>
			{% else %}
			<a href="#" class="muted">
				{{ poll.question }}
			</a> (Votacións desactivadas)
			{% endif %}

			{% if perms.polls.vote_count %}
			Usuarios que votaron: {{ poll.get_votes.get_users }}
			{% endif %}

			{% if perms.polls.poll_results %}
			--
			<a href="{% url "polls:results" poll.id %}">
				(Ver resultados)
			</a>
			{% endif %}
		</li>
	{% endfor %}
	</ul>

{% else %}

<p>Non hai encuestas activas neste momento.</p>

{% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends "site_base.html" %}
{% block title %}Resultados da votación da Orla{% endblock %}
{% block content %}
<h1>{{ poll.question }}</h1>

<ol>
{% for vote in poll.get_votes.all %}
    <li>
    <span style="min-width: 20em; display:inline-block">{{ vote.choice__choice_text }}</span>

        {% if perms.polls.full_results %}
        <strong>{{vote.number__count}}</strong> votos, total de <strong>{{ vote.number__sum }}</strong> puntos</li>

        {% endif %}
{% endfor %}
</ol>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
{% endblock %}