orlaudc/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from django.contrib.auth.views import login

from cas_client import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'orlaudc.views.home', name='home'),
    # url(r'^orlaudc/', include('orlaudc.foo.urls')),

    url (r'^$', csrf_exempt(TemplateView.as_view(template_name="home.html")),
            name='home'),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^cas/', include('cas_client.urls')),

    url(r'^accounts/login/$',
    		TemplateView.as_view(template_name="accounts_login.html"),
    		name='accounts_login'),

    url(r'^accounts/local_login$', login, name="login"),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

)
urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

from polls import views

# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote$', views.vote, name='vote'),

    url(r'^(?P<poll_id>\d+)/add_choice$', views.add_choice, name='add_choice'),


    url(r'^(?P<poll_id>\d+)/bulk$', permission_required("polls.bulk")(TemplateView.as_view(template_name="polls/bulk_form.html")), name='bulk'),
    url(r'^(?P<poll_id>\d+)/bulk/upload$', views.bulk_upload, name='bulk_upload'),

)

templates/accounts_login.html
{% extends "site_base.html" %}
{% block content %}

<div style="max-width: 70%">
<p>
	Esta aplicación web permite iniciar sesión mediante tickets dun servidor <abbrev title="Central Authentication Service">CAS</abbrev>.
</p>

<p>
	Deste xeito esta aplicación <strong>non terá acceso</strong> ao teu contrasinal, e ao mesmo tempo poderase validar que és un membro da comunidade coa que queres participar.
</p>

<form>
{% load add_get_parameter %}
<a href="{% url "cas-redirect" %}{% add_get %}">
	<img src="http://www.udc.es/export/system/modules/es.udc.portal/resources/_img/cabecera/udc_logo.png" alt="Universidade da Coruña" title="Universidade da Coruña" />
</a>
</form>

</div>

{% endblock %}

templates/home.html
{% extends "site_base.html" %}
{%block content %}
<h1>Benvido</h1>
<p>
Benvido ao sistema de votación de profesores para a Orla de 5º de Enxeñería Informática da UDC.
</p>

<a href="{% url "polls:index" %}">Pulsa aquí para ver as votacións en curso.</a>

{% if not user.is_authenticated %}
<div id="cookielaw">
	<h2>Requsito de satisfacción coa Lei de Cookies Europea</h2>

	<p>
		Segundo a nova (estúpida) directiva europea de cookies, é preciso que
		antes de poñer cookies non esenciales para o uso do servizo se informe
		e pregunte sobre dito emplazamento de cookies.
	</p>

	<p>
		En calquera caso, estas cookies configuradas por terceiras partes poden ser deshabilitadas polo seu navegador mediante as opcións de cookies, preferindo non aceptar cookies de terceiros.
	</p>

	<p>
		Permite que este sitio web empregue cookies non esenciais?
	</p>

	<!-- As cookies csrftoken e sessionid son consideradas esenciais para poder prestar o servizo deste sitio web -->
</div>

<script type="text/javascript">
$(function() {
	$( "#cookielaw" ).dialog({
		height: 440,
		width: 400,
		modal: true,
		buttons: {
			Si: function() {
				$( this ).dialog( "close" );
			},
			Non: function() {
				$( this ).dialog( "close" );
				var objs = document.getElementsByTagName('a')
				$( objs ).each(function(idx, dom) {
					dom.href = "#"
					dom.className += " disabled"
				})
			}
		}
	})
})
</script>
{% endif %}

{% endblock %}
{% block ananlytics %}<!-- Analytics removed on main page for EU-cookie policy compliancy -->{% endblock %}

templates/site_base.html
<!DOCTYPE html>
{% load dajaxice_templatetags %}
<html>
<head>
{% load static from staticfiles %}
<title>{% block title %}Orla UDC para Ingeniería Informática{% endblock %}</title>
<meta charset="utf-8" />
<meta http-equiv="Author" content="Santiago Saavedra López" />
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
<link rel="stylesheet" href="{% static "css/main.css" %}" />
<script type="text/javascript" src="{% static "js/jquery-1.9.1.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery-ui-1.10.3.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
<script type="text/javascript" src="{% static "/static/dajax/jquery.dajax.core.js" %}"></script>
    {% dajaxice_js_import %}

<script type="text/javascript">
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
        // or any other URL that isn't scheme relative or absolute i.e relative.
        !(/^(\/\/|http:|https:).*/.test(url));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
            // Send the token to same-origin, relative URLs only.
            // Send the token only if the method warrants CSRF protection
            // Using the CSRFToken value acquired earlier
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        }
    }
});
</script>

<style type="text/css">
{% block style %}
{% endblock %}
</style>

</head>
<body>

<div id="topnav">
<div id="login_bar">
{% if user.is_authenticated %}
User: {{ user.login }} | <a href="{% url "cas-logout" %}">Logout</a>
{% else %}
You are anonymous. <a href="{% url "accounts_login" %}">Login</a>
{% endif %}
</div>
</div>

<div id="content" class="clearfix" style="clear:both">
{% block content %}{% endblock %}
</div>

{% block analytics %}
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45463320-1', 'herokuapps.com');
  ga('send', 'pageview');

</script>
{% endblock %}
<footer class="site-footer muted copyright well well-small">
    Santiago Saavedra López. Código disponible en breve en <a rel="me" href="https://github.com/ssaavedra">GitHub</a>.
    <br />
    <a href="http://twitter.com/intent/tweet?text=%40ssice%20%23orlabug:&related=ssice">Dudas / No funciona?</a>
</footer>
</body>
</html>